version: '3.7'

services:
  b2note-nodejs:
    image: b2note/b2note-nodejs:3.0-alpha2
    restart: always
    network_mode: host
    depends_on: 
      - mongo
    build: .
    environment:
      NODE_ENV: production
    env_file:
      ./.env
    ports:
      - 3060:3060
  mongo:
    image: mongo
    command: mongod --port 27018
    restart: always
    network_mode: host
    volumes:
      - type: volume
        source: mongodbdata
        target: /data/db
    ports:
      - 27018:27018

volumes:
  mongodbdata: